### PR TITLE
Add @rollup/rollup-darwin-arm64 package

### PR DESCRIPTION
**Pull request by Mearman**

### CODE REVIEW

**Comment by PaulKinlan** [comment]
This is more due to package-lock getting out of date because we use different development platforms.

**Comment by PaulKinlan** [comment]
Also I think I saw a note somewhere that this should be in "peerDependencies" (but I'm not quite sure)

**Comment by aomarks** [comment]
We might want to put both the x86 and darwin packages in the "optionalDependencies" field in the top-level package.json so that `npm ci` works on either architecture?

https://github.com/npm/cli/issues/4828#issuecomment-1848965606
https://docs.npmjs.com/cli/v10/configuring-npm/package-json#optionaldependencies

**Comment by aomarks** [comment]
I think this is fixed in https://github.com/breadboard-ai/breadboard/commit/85f695bf101d7ca4552471aa1797a401f49bd69c

**Pull request closed without merging**
