### PR TITLE
Ava tsx

### PR DESCRIPTION
**Pull request by Mearman**

### CODE REVIEW

**Comment by Mearman** [comment]
I think this is good to go now @dglazkov

**Comment by dglazkov** [comment]
I remember @aomarks having concerns about switching to tsx.

**Comment by Mearman** [comment]
> I remember @aomarks having concerns about switching to tsx.

I was considering there are could be both `test:ts` and `test:js` scripts to allow more exhaustively running the tests, such as in CI?

**Comment by aomarks** [comment]
Hi @Mearman!

I can definitely see the appeal of using tsx before Wireit was set up, because it would have meant we wouldn't have to remember to compile the package before running tests. But now that wireit is set up, we already have a solution to that problem, since now when you run `npm test`, wireit now ensures that the local package gets compiled if needed, along with all of the dependency packages too. And that has the nice characteristic that we're testing the exact same `.js` files that we'd be publishing to npm. WDYT?

**Comment by Mearman** [comment]
@aomarks hmm.
running TS tests against TS source and for example picked up this that passes on JS.
https://github.com/google/labs-prototypes/actions/runs/7164352098/job/19504258289#step:9:266

Once the JS is built, like you say it is more like the runtime environment, but it's a more relaxed environment.

So I think there's value to having and being able to be more exhaustive and use both, such as on CI/CD.

**Comment by aomarks** [comment]
> @aomarks hmm. running TS tests against TS source and for example picked up this that passes on JS. https://github.com/google/labs-prototypes/actions/runs/7164352098/job/19504258289#step:9:266
> 
> Once the JS is built, like you say it is more like the runtime environment, but it's a more relaxed environment.

Interesting! I believe tsx works by intercepting Node module loading calls and dynamically converting TS files to JS by calling esbuild. esbuild is a 3rd party alternative to the official ts compiler which doesn't do any type checking, and can diverge from the official compiler in terms of features/bugs (its selling point is mostly being very fast).

So I'm really curious what's going on here with this failure! It could be an esbuild bug which just produces broken code, or it could be a bug with tsx doing its module injection? There is a warning at https://github.com/avajs/ava/blob/main/docs/recipes/typescript.md#mocking saying that tsx doesn't work with mocking libraries, which could be some kind of clue? I don't actually know enough about the breadboard code yet to have any intuition what could cause `runOnce` to resolve to `undefined` instead of a `string`.

**Comment by Mearman** [comment]
@aomarks yeah, I don't know enough about the minutiae to be certain either.

**Comment by aomarks** [comment]
Breadboard has graduated to a new dedicated repo! 🎉 🎓 We were able to transfer everything except for open PRs, so this one will need to be re-created at https://github.com/breadboard-ai/breadboard/pulls if it is still relevant. Thank you! Sorry for the disruption.

**Pull request closed without merging**
