### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Chizobaonorh**
Generated documentations for seeds/breadboards and seed/llm starter.

### CODE REVIEW

**Review by dglazkov — COMMENTED** [review]
Alright! We're definitely moving in the right direction. It looks like the tool generates the files!

When I go look at the contents of `/seeds/llm-starter/docs/modules.html`, I don't actually see any classes or methods. I wonder why?

I am guessing that somehow, the tool isn't picking up the actual source files (the ones in `/seeds/llm-starter/src/`) to use to prepare docts?

**Comment by Chizobaonorh** [comment]
> Alright! We're definitely moving in the right direction. It looks like the tool generates the files!
> 
> When I go look at the contents of `/seeds/llm-starter/docs/modules.html`, I don't actually see any classes or methods. I wonder why?
> 
> I am guessing that somehow, the tool isn't picking up the actual source files (the ones in `/seeds/llm-starter/src/`) to use to prepare docts?

I think maybe because i didn't cd into src but generated it from the llm-starter root level, let me do that now.

**Comment by Chizobaonorh** [comment]
> > Alright! We're definitely moving in the right direction. It looks like the tool generates the files!
> > When I go look at the contents of `/seeds/llm-starter/docs/modules.html`, I don't actually see any classes or methods. I wonder why?
> > I am guessing that somehow, the tool isn't picking up the actual source files (the ones in `/seeds/llm-starter/src/`) to use to prepare docts?
> 
> I think maybe because i didn't cd into src but generated it from the llm-starter root level, let me do that now.

Okay i tried this, but it didn't regenerate any more docs, maybe you can check the codes too for something we can tweak to make it generate the modules and classes.

**Comment by dglazkov** [comment]
> maybe you can check the codes too for something we can tweak to make it generate the modules and classes.

will do!

**Comment by Chizobaonorh** [comment]
> > maybe you can check the codes too for something we can tweak to make it generate the modules and classes.
> 
> will do!

any update on this?

**Comment by dglazkov** [comment]
not yet -- my apologies, my day had completely run away from me.

**Comment by dglazkov** [comment]
Okay, I had a chance to take a look. Here's a couple of things that will help produce the docs:
- Run `npm install --save-dev typedoc` in `seeds/llm-starter`. This will install the typedoc for this package (you will see it as a change in `package.json`)
- Modify `seeds/llm-starter/tsconfig.json` just like you've done for `seeds/breadboard/tsconfig.json`. Since these are two separate Node packages, we need this change for each package.
- Specify [`entryPoints`](https://typedoc.org/options/input/#entrypoints) in the `seeds/breadboard/tsconfig.json`, pointing it to `"./src/index.ts"` This will allow TypeDoc see the source files to document. (✨  this was the missing piece).
- Now, you can run `npx typedoc` to generate documentation!

I hope this helps. When it runs, it now generates a ton of warnings -- all of which seem like useful information to start working through.


As the next step, let's see if we can get the [markdown plugin](https://www.npmjs.com/package/typedoc-plugin-markdown) going. This way, instead of `.html` files, we'll se a bunch of MD files in `./docs`.

**Comment by Chizobaonorh** [comment]
okay, already working on it.

**Comment by Chizobaonorh** [comment]
I am having serious issues with this new command:

src/board.ts:16:8 - error TS2307: Cannot find module '@google-labs/graph-runner' or its corresponding type declarations.

16 } from "@google-labs/graph-runner";
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~



i need help!

**Comment by dglazkov** [comment]
> Cannot find module '@google-labs/graph-runner' or its corresponding type declarations.

This error tells me that the repository hasn't yet been correctly set up. Were you able to run `npm i` in the root of the repository? This error will go away as soon as you have done so.

Just to give you a mental model:

- the repository is set up as a group of interrelated Node.js packages in as so-called "monorepo" configuration. You can read more about the monorepo concept here: https://monorepo.tools/
- these Node.js packages depend on each other. For example `@google-labs/breadboard` package (located in `/seeds/breadboard` depends on `@google-labs/graph-runner` package (located in `/seeds/graph-runner`).
- for these dependencies to work correctly, we need to the `npm` tool to create the underlying connections (they are created in `node_modules` directory).
- This is what running `npm i` does.

Does that make sense?

**Comment by Chizobaonorh** [comment]
Yes it does, let me do that now

**Comment by Chizobaonorh** [comment]
I have done this and it is still doing the same thing.

**Pull request closed without merging**
