### PR TITLE
[WIP] Add a "Web seed"

### LINKED ISSUE #51: [Working log] Attempting to build a web app that uses graph-*
For Dimitri. This is a working log of all the issues I hit trying to get things working in the browser.

Goal 1: Build a web app that uses palm-lite
Goal 2: Build a web app that creates a breadboard programatically and runs it (using Starter Kit)
Goal 3: Build a web app that loads a graph and shows the mermaid view
Goal 4: Build a web app that loads a graph and runs it.
Goal 5: TBD

Environment: Preact, Typescript, Vite.

# Goal 1

Palm-lite is confirmed to work in the browser. It hasn't got dependencies that are not Node or Browser compatible.

+ [x] Palm-lite 
  + [x] Text Completion
  + [x] Chat
  + [x] Embedding

# Goal 2 - Build a web app that creates a breadboard programatically and runs it (using Starter Kit)

The simplest demo that does something useful should call the Palm API. The demo should request the API key, 

+ [ ] Create a breadboard
  + [x] Add the Starter Kit
  + [ ] Use API_Key Secrets: FAIL - the code in secrets.ts uses `process` which is not available to the browser `    .map((key) => [key, process.env[key]])`. You can make an global though.

```
window.process = {};
window.process.env = {};
window.process.env.API_KEY = apiKey;
```

# Goal 3

Broadly works if you remove the references to `kits` which can't currently be loaded.

Update: now that the kit is published, might be easier.

# Goal 4

1. To load a graph I need to use a `breadboard`. 
  `import { Board, type ProbeEvent } from "@google-labs/breadboard";` causes an error because it relies on an `readFile` from `fs/promise` [here](https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/src/board.ts#L31). It is only used if we provide a path to `loadGraph`, Remove the import and dynamically import readFile only when a file path is included:
  ```
  export const loadGraph = async (path?: string, ref?: string) => {
    if (path) { 
       const { readFile } = await import("node:fs/promise")
       return JSON.parse(await readFile(path, "utf-8"));
    }
    if (!ref) throw new Error("To include, we need a path or a $ref");
    const response = await fetch(ref);
    return await response.json();
  };
  ```
  Update: Tested and it stops the error.

2. KitLoader fails to dynamically import using vite as a bundler. When people are building sites they tend to use a bundler, and the bundler has to know about all the assets it needs to compile. I was trying `simplest.json` and it includes a kit `"url": "npm:@google-labs/llm-starter"` which will not be able to be loaded in the browser because the bundler 1) doesn't know about it, and 2) if we changed it to "http:" for a dynamic import we'd need to host it some where.
  * Note: maybe just copy it in for now?
  * Update: URLs have to be "Npm spec"... weird.

### PR DESCRIPTION
**Pull request by PaulKinlan**
Fixes #51 - this PR is for your visibility and I don't think is something that should be merged yet.

> It's a good idea to open an issue first for discussion.

- [ ] Tests pass
- [ ] Appropriate changes to documentation are included in the PR

This PR get's the breadboard and llm-starter ready for running in a browser. The summary of changes are:

+ Remove direct nodejs imports (and make them dynamic)
+ Change `secrets` to pull from the user-context vs put on the `process.env` - i.e the graph runner will ask your user-space code for a bag of things to resolve the secrets.
+ Add a web-demo so that we can play with different parts of this project.
  + We are unable to resolve "npm:" url's for kits right now, so a graph file has to have "npm:https://esm.sh/@google-labs/llm-starter"

  + We don't yet have a node editor in this.
  + The UI currently has
     1. A Palm-lite tester.
     2. A "completion" test harness that uses the imperative Board API.
     2. A breadboard viewer 
Screenshot 2023-08-08 at 23 00 36
  +

### CODE REVIEW

**Comment by dglazkov** [comment]
> We are unable to resolve "npm:" url's for kits right now, so a graph file has to have "npm:https://esm.sh/@google-labs/llm-starter"

Interesting! We don't load npm packages in Node. They have to be explicitly installed as dependencies, and the `kits` reference only attempts to import them. With the `esm.sh`, the meaning changes, since now we're actually installing them. Is there a way in vite to say: "hey, I will dynamically import this package later, please keep it around"?

**Comment by PaulKinlan** [comment]
> They have to be explicitly installed as dependencies

At least for how I envisage using graph files (sharing etc), we have to have a way to load kits without knowing about them ahead of time. If I share a graph with you, you then have to parse the json file, find the kits, add them to your project as dependencies...urgh. This might be fine if it's a static project, but for sharing it doesn't really work. If Kits have to be hard dependencies, then it feels kinda weird that we would have a definition defined in a JSON file at all *and* then have it hardcoded in the code that loads and runs the graph. 

Right now you dynamically load models through the `KitLoader`, I'd probably just do `Board.load("path to graph", {kits: [LLMStarter]})`. Or something like that.

> With the esm.sh, the meaning changes, since now we're actually installing them. Is there a way in vite to say: "hey, I will dynamically import this package later, please keep it around"?

We're not installing them, it's all dynamically downloaded and imported at runtime when the we call `Board.load`. For the viewer that I was building there is no way to know that for any given graph file what kits are included. If the Kit isn't accessible I can't even render the graph, let alone run it.

To test these changes for example, I've uploaded my own kit. https://www.npmjs.com/package/@paulkinlan/llm-starter - I thought that was neat.

**Comment by dglazkov** [comment]
My hope is to turn boards to Kits. The basic idea is that Kits are just boards without wires. I'd like to eliminate the concept of boards as npm packages altogether.

See: https://github.com/google/labs-prototypes/issues/36#issuecomment-1664799621

**Comment by seefeldb** [comment]
> My hope is to turn boards to Kits. The basic idea is that Kits are just boards without wires. I'd like to eliminate the concept of boards as npm packages altogether.
> 
> See: [#36 (comment)](https://github.com/google/labs-prototypes/issues/36#issuecomment-1664799621)

Also see #58 for a previous discussion of loading npm packages.

Pragmatically I think we want to
 - not ship this with a giant security hole, so at least need an allowlist or so as a temporary protection (which having to manually install a package is effectively in the node environment)
 - be able to use the web interface while developing a kit, so avoid having to publish a package for every iteration

Since we'll want to move from npm to graphs-as-kits for kits anyway before sharing graphs with new kits is an actual thing, is there something quick we can do for now that unblocks this? Let's assume everyone builds from the repo for example.

**Comment by PaulKinlan** [comment]
I will close the PR and open a new one that has all the commits squashed so it doesn't poluate all your histories.

**Pull request closed without merging**
