### PR TITLE
Add local file tests

### PR DESCRIPTION
**Pull request by Mearman**

### CODE REVIEW

**Comment by Mearman** [comment]
these are the two places that I think this could be resolve least disruptively:
- https://github.com/ExaDev-io/labs-prototypes/commit/97fc7d9d53d639ae02dfb1a5c42b11c3badd7a30#diff-296fc4a0e792ae1a11d5c16a284b6aded6f0637f7fe2f359d71b2cd590ca4374R35
- https://github.com/ExaDev-io/labs-prototypes/commit/74b0433ec43d4fdaa697aa2d5c786ffdfba9a030#diff-296fc4a0e792ae1a11d5c16a284b6aded6f0637f7fe2f359d71b2cd590ca4374R60

Green across the board for both changes. @dglazkov are there any cases you can think of that this might break?

**Comment by dglazkov** [comment]
Ohhh, is the bug that `readFile` doesn't accept URLs? So it needs to have the path part of the URL decoded?

**Comment by dglazkov** [comment]
Thank you for writing these tests! They are a bit too chunky -- test more than they need to. I would instead write a unit test for the `resolveURL` in `loader.ts`.

**Comment by dglazkov** [comment]
> Green across the board for both changes. @dglazkov are there any cases you can think of that this might break?

The change in `loadFromFile` seems right, since it's localizes the knowledge of how to load files there. Thank you for spotting it!

Would you be up for rewriting the unit test for just `loadFromFile`?

**Comment by Mearman** [comment]
> > Green across the board for both changes. @dglazkov are there any cases you can think of that this might break?
> 
> The change in `loadFromFile` seems right, since it's localizes the knowledge of how to load files there. Thank you for spotting it!
> 
> Would you be up for rewriting the unit test for just `loadFromFile`?

sure thing. I'll bring in the change for `loadFromFile` and revise the tests.

**Comment by Mearman** [comment]
@dglazkov. for the chunkier tests, they definitely ended up going more towards integrationey tests.
But I think they still might be adding coverage.
IF we were to keep theses tests or similar, less-atomic tests, where should they live?

**Comment by aomarks** [comment]
Breadboard has graduated to a new dedicated repo! 🎉 🎓 We were able to transfer everything except for open PRs, so this one will need to be re-created at https://github.com/breadboard-ai/breadboard/pulls if it is still relevant. Thank you! Sorry for the disruption.

**Pull request closed without merging**
