### PR TITLE
add generation of dependency cycle visualisation

### PR DESCRIPTION
**Pull request by Mearman**

### CODE REVIEW

**Comment by PaulKinlan** [comment]
Neat - madge is what I was using.

**Comment by PaulKinlan** [comment]
If I run the command `npx -y madge --circular --image cycles.svg --extensions ts ./` I get `Graphviz could not be found. Ensure that "gvpr" is in your $PATH. Error: spawn gvpr ENOENT`

**Comment by Mearman** [comment]
Oh yeah @PaulKinlan it needs GraphViz to convert out to the SVG

**Comment by PaulKinlan** [comment]
One thing that I noticed is that the current build we have detects cycles via `rollup`, it only shows it in the `dist` folder, but it's pretty much the same result.

**Comment by aomarks** [comment]
Breadboard has graduated to a new dedicated repo! 🎉 🎓 We were able to transfer everything except for open PRs, so this one will need to be re-created at https://github.com/breadboard-ai/breadboard/pulls if it is still relevant. Thank you! Sorry for the disruption.

**Pull request closed without merging**
